server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 416424
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always

logging:
  level:
    com.ead: DEBUG # (TRACE - DEBUG - INFO - WARN - ERROR)
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG

ead:
  api:
    url:
      course: 'http://localhost:8082'