spring:
  config:
#    import: 'optional:configserver:'
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 416424