ead:
  serviceRegistry:
    username: serviceregistry
    password: 416424
  auth:
    jwtSecret: C4YAnyjeruQ7wnFApzDDZcGLXWWq4qjVXnwiEx68bk3lS2H769zbO3aKfBkgKCFQ
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost