ead:
  serviceRegistry:
    username: serviceregistry
    password: 416424
  auth:
    jwtSecret: tJds--Lbwa-s0G5AY-0OFFJ_TlTXSQdPaBhGqRxm4XXnC08tVyo43aVN_lNlDcrt7VmBU6orIi8gHTeRjGkxfA
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost