ead:
  serviceRegistry:
    username: serviceregistry
    password: 416424
  auth:
    jwtSecret: Ixl4_0Uv9RohXUYF4c9wSw7Ehtc5zxJqkleYfC37cJFOXOofNqq6oUfb7lVDQeqQdWcq1fqR69oafuZuZ2vTJg
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost